# version: "2.1"

services:
  unifi-db:
    image: docker.io/mongo:4.4
    container_name: unifi-db
    volumes:
      - /opt/unifi/data/db:/data/db
      - /opt/unifi/data/configdb:/data/configdb
      - /opt/unifi/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    logging:
        driver: "json-file"
        options:
            max-file: 2
            max-size: 10m
    restart: unless-stopped
    
  unifi-network-server:
    image: lscr.io/linuxserver/unifi-network-application:8.2.93
    container_name: unifi-network-server
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
      - MONGO_USER=unifi
      - MONGO_PASS=unifi
      - MONGO_HOST=unifi-db
      - MONGO_PORT=27017
      - MONGO_DBNAME=unifi
      - MEM_LIMIT=1024
      - MEM_STARTUP=1024
      # - MONGO_TLS=
      # - MONGO_AUTHSOURCE=
    volumes:
      - /opt/unifi:/config
    ports:
      - 8443:8443
      - 3478:3478/udp
      - 10001:10001/udp
      - 8080:8080
      - 1900:1900/udp
      - 8843:8843
      - 8880:8880
      - 6789:6789
      - 5514:5514/udp
    logging:
        driver: "json-file"
        options:
            max-file: 2
            max-size: 10m
    restart: unless-stopped
